# Generated by Django 2.2.6 on 2019-10-29 06:27

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Enter Tag keyword', max_length=155, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter service title', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=services.models.upload_service_image_path)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='services.Category')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
