# Generated by Django 2.2.6 on 2019-10-29 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('person', '0004_auto_20191029_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('short_note', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('city', models.CharField(default='Dhaka', max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('country', models.CharField(default='Bangladesh', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.CharField(choices=[('create', 'Create'), ('pending', 'Pending'), ('confirm', 'Confirm'), ('ongoing', 'OnGoing'), ('completed', 'Completed'), ('rated', 'Rated')], default='create', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Expert')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
