# Generated by Django 2.2.6 on 2020-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191102_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('create', 'Create'), ('pending', 'Pending'), ('confirm', 'Confirm'), ('ongoing', 'OnGoing'), ('completed', 'Completed'), ('rated', 'Rated'), ('cancel', 'Cancel')], default='create', max_length=120),
        ),
    ]
