# Generated by Django 2.2.6 on 2019-10-29 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=person.models.upload_person_image_path)),
                ('designation', models.CharField(max_length=255)),
                ('Objective', models.TextField(blank=True, null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
    ]
