# Generated by Django 2.2.6 on 2019-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
