# Generated by Django 2.2.6 on 2019-10-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_expert_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('training_institute', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('average', 'Average'), ('skilled', 'Skilled'), ('specialist', 'Specialist'), ('expert', 'Expert')], default='average', max_length=120)),
                ('is_verify', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Expert')),
            ],
        ),
    ]
